import React from "react";

function Example() {
  return (
    <div className="text-center justify-items-center text-2xl p-36 sm:p-0 mt-36 font-bold text-white">
      <h1>Do not edit this file</h1>
        <h2>Everything goes into Staging Branch</h2>
    </div>
  );
}

export default Example;
