import React from "react";

function Example() {
  return (
<<<<<<< HEAD
    <div className="text-2xl font-bold text-center text-white justify-items-center p-36 sm:p-0 mt-36">
=======
    <div className="text-center justify-items-center text-2xl p-36 sm:p-0 mt-36 font-bold text-white">
>>>>>>> b90daf6af170e8190324fa3c434013d5ac82b681
      <h1>Do not edit this file</h1>
        <h2>Everything goes into Staging Branch</h2>
    </div>
  );
}

export default Example;
