import React from "react";

function Example() {
  return (
    <div className="text-2xl font-bold text-center text-white justify-items-center p-36 sm:p-0 mt-36">
      <h1>Do not edit this file</h1>
        <h2>Everything goes into Staging Branch</h2>
    </div>
  );
}

export default Example;
